export enum GameMode {
  REFX_OSU = 0,
  REFX_TAIKO = 1,
  REFX_CATCH = 2,
  REFX_MANIA = 3,
  SHAYMI_OSU = 4,
  SHAYMI_TAIKO = 5,
  SHAYMI_CATCH = 6,
  SHAYMI_MANIA = 7,
  AUTOPILOT_OSU = 8,
  AUTOPILOT_TAIKO = 9,
  AUTOPILOT_CATCH = 10,
  AUTOPILOT_MANIA = 11,
  CHEAT_OSU = 12,
  CHEAT_TAIKO = 13,
  CHEAT_CATCH = 14,
  CHEAT_MANIA = 15,
  CHEAT_CHEAT_OSU = 16,
  CHEAT_CHEAT_TAIKO = 17,
  CHEAT_CHEAT_CATCH = 18,
  CHEAT_CHEAT_MANIA = 19,
  TOUCH_DEVICE_OSU = 20,
}

export const INVALID_MODES = new Set([
  GameMode.AUTOPILOT_CATCH,
  GameMode.AUTOPILOT_TAIKO,
  GameMode.AUTOPILOT_MANIA,
]);

export const VALID_SCORE_MODES = [
  GameMode.REFX_OSU,
  GameMode.REFX_TAIKO,
  GameMode.REFX_CATCH,
  GameMode.REFX_MANIA,
  GameMode.SHAYMI_OSU,
  GameMode.SHAYMI_TAIKO,
  GameMode.SHAYMI_CATCH,
  GameMode.AUTOPILOT_OSU,
];
